---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CP-Cluster
  region: us-east-1
  version: "1.18"

nodeGroups:
  - name: ng3-private-b
    instanceType: t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    taints:
      - key: special
        value: "true"
        effect: NoSchedule
    



    
