apiVersion: v1
kind: Pod
metadata:
  name: redis-cli
  labels:
    app: redis-cli
  namespace: demo
spec:
  containers:
  - image: redis:6.2-alpine
    command:
      # - "/bin/sh"
      - "sleep"
      - "100000"
    imagePullPolicy: IfNotPresent
    name: redis-cli
  restartPolicy: Always