---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: demo
  labels:
    team: CP-Project
spec:
  endpoints:
  - honorLabels: true
    port: web
  selector:
    matchLabels:
      operated-prometheus: "true"